export default {
	plugins: ["oxc", "typescript", "unicorn", "react", "vue"],
	jsPlugins: [
		"@stylistic/eslint-plugin",
		{
			name: "vite-plus",
			specifier: "vite-plus/oxlint-plugin",
		},
	],
	categories: {
		correctness: "warn",
	},
	env: {
		builtin: true,
		browser: true,
	},
	globals: {
		defineEmits: "readonly",
		defineExpose: "readonly",
		defineModel: "readonly",
		defineOptions: "readonly",
		defineProps: "readonly",
		defineSlots: "readonly",
		withDefaults: "readonly",
	},
	ignorePatterns: [
		"**/dist/*",
		"**/dist-docs/*",
		"support/",
		".codebase-memory/**",
		".boilersuit/**",
	],
	rules: {
		"constructor-super": "error",
		"for-direction": "error",
		"getter-return": "error",
		"no-async-promise-executor": "error",
		"no-case-declarations": "error",
		"no-class-assign": "error",
		"no-compare-neg-zero": "error",
		"no-cond-assign": "error",
		"no-const-assign": "error",
		"no-constant-binary-expression": "error",
		"no-constant-condition": "error",
		"no-control-regex": "error",
		"no-debugger": "error",
		"no-delete-var": "error",
		"no-dupe-class-members": "error",
		"no-dupe-else-if": "error",
		"no-dupe-keys": "error",
		"no-duplicate-case": "error",
		"no-empty": "error",
		"no-empty-character-class": "error",
		"no-empty-pattern": "error",
		"no-empty-static-block": "error",
		"no-ex-assign": "error",
		"no-extra-boolean-cast": "error",
		"no-fallthrough": "error",
		"no-func-assign": "error",
		"no-global-assign": "error",
		"no-import-assign": "error",
		"no-invalid-regexp": "error",
		"no-irregular-whitespace": "error",
		"no-loss-of-precision": "error",
		"no-misleading-character-class": "error",
		"no-new-native-nonconstructor": "error",
		"no-nonoctal-decimal-escape": "error",
		"no-obj-calls": "error",
		"no-prototype-builtins": "error",
		"no-redeclare": "error",
		"no-regex-spaces": "error",
		"no-self-assign": "error",
		"no-setter-return": "error",
		"no-shadow-restricted-names": "error",
		"no-sparse-arrays": "error",
		"no-this-before-super": "error",
		"no-unassigned-vars": "error",
		"no-undef": "error",
		"no-unexpected-multiline": "error",
		"no-unreachable": "error",
		"no-unsafe-finally": "error",
		"no-unsafe-negation": "error",
		"no-unsafe-optional-chaining": "error",
		"no-unused-labels": "error",
		"no-unused-private-class-members": "error",
		"no-unused-vars": "error",
		"no-useless-assignment": "error",
		"no-useless-backreference": "error",
		"no-useless-catch": "error",
		"no-useless-escape": "error",
		"no-with": "error",
		"preserve-caught-error": "error",
		"require-yield": "error",
		"use-isnan": "error",
		"valid-typeof": "error",
		"vue/no-arrow-functions-in-watch": "error",
		"vue/no-deprecated-data-object-declaration": "error",
		"vue/no-deprecated-delete-set": "error",
		"vue/no-deprecated-destroyed-lifecycle": "error",
		"vue/no-deprecated-events-api": "error",
		"vue/no-deprecated-model-definition": "error",
		"vue/no-deprecated-vue-config-keycodes": "error",
		"vue/no-export-in-script-setup": "error",
		"vue/no-lifecycle-after-await": "error",
		"vue/prefer-import-from-vue": "error",
		"vue/return-in-computed-property": "error",
		"vue/valid-define-emits": "error",
		"vue/valid-define-props": "error",
		"vue/no-multiple-slot-args": "warn",
		"vue/no-required-prop-with-default": "warn",
		"@stylistic/no-confusing-arrow": "error",
		"@stylistic/padding-line-between-statements": [
			"error",
			{
				blankLine: "always",
				prev: "const",
				next: "let",
			},
			{
				blankLine: "always",
				prev: "let",
				next: "const",
			},
			{
				blankLine: "always",
				prev: "*",
				next: "break",
			},
			{
				blankLine: "always",
				prev: ["const", "let"],
				next: "*",
			},
			{
				blankLine: "always",
				prev: "*",
				next: "return",
			},
			{
				blankLine: "any",
				prev: "const",
				next: "const",
			},
			{
				blankLine: "any",
				prev: "let",
				next: "let",
			},
			{
				blankLine: "always",
				prev: "multiline-const",
				next: "*",
			},
			{
				blankLine: "always",
				prev: "*",
				next: "multiline-const",
			},
		],
		"vite-plus/prefer-vite-plus-imports": "error",
	},
	overrides: [
		{
			files: ["**/*.cy.js", "test/cypress/support/*.js"],
			rules: {
				"cypress/no-assigning-return-values": "error",
				"cypress/no-unnecessary-waiting": "error",
				"cypress/no-async-tests": "error",
				"cypress/unsafe-to-chain-command": "error",
			},
			jsPlugins: ["eslint-plugin-cypress"],
			globals: {
				cy: "readonly",
				Cypress: "readonly",
				expect: "readonly",
				assert: "readonly",
				chai: "readonly",
			},
			env: {
				mocha: true,
			},
		},
	],
	options: {
		typeAware: false,
		typeCheck: false,
	},
};
