import DataTable from "./data-table.vue";
import { createMount } from "@unit/support/mount";
import { describe, expect, test } from "vite-plus/test";
import { get } from "@lewishowles/helpers/object";
import { nextTick } from "vue";

const sampleRow = { id: "123", title: "Toy Story", release_year: "1995" };
const defaultProps = { data: [sampleRow] };
const mount = createMount(DataTable, { props: defaultProps });

describe("data-table", () => {
	// A mock "standardised" row as generated by the data-table internals for
	// testing.
	const standardisedRow = {
		id: {
			configuration: {
				searchable: "123",
				sortable: "123",
			},
			content: "123",
		},
		title: {
			configuration: {
				searchable: "toy story",
				sortable: "toy story",
			},
			content: "Toy Story",
		},
		release_year: {
			configuration: {
				searchable: "1995",
				sortable: "1995",
			},
			content: "1995",
		},
	};

	// A standard column definition for testing.
	const baseColumnDefinition = {
		first: false,
		last: false,
		sortable: true,
		tabularNums: false,
		visible: true,
	};

	describe("Initialisation", () => {
		test("should exist as a Vue component", () => {
			const wrapper = mount();

			expect(wrapper.vm).toBeTypeOf("object");
		});
	});

	describe("Render contracts", () => {
		test("should expose the component styling hook", () => {
			const wrapper = mount();

			expect(wrapper.attributes("data-component")).toBe("data-table");
		});
	});

	describe("Computed", () => {
		describe("columnDefinitions", () => {
			test("should handle there being no data present", () => {
				const wrapper = mount({ data: [] });
				const vm = wrapper.vm;

				expect(vm.columnDefinitions).toEqual({});
			});

			test("should determine which column is first, and which is last", () => {
				const columns = {
					id: { label: "ID" },
					title: { label: "Title" },
					release_year: { label: "Release year" },
				};

				const wrapper = mount({ columns });
				const vm = wrapper.vm;

				expect(vm.columnDefinitions).toEqual({
					id: {
						...baseColumnDefinition,
						label: "ID",
						first: true,
					},
					title: {
						...baseColumnDefinition,
						label: "Title",
					},
					release_year: {
						...baseColumnDefinition,
						label: "Release year",
						last: true,
					},
				});
			});

			test("should retrieve column configuration where found", () => {
				const columns = {
					title: { label: "Title" },
					release_year: { label: "Release year", columnClasses: "text-right" },
				};

				const wrapper = mount({ columns });
				const vm = wrapper.vm;

				expect(vm.columnDefinitions).toEqual({
					title: {
						...baseColumnDefinition,
						label: "Title",
						first: true,
					},
					release_year: {
						...baseColumnDefinition,
						label: "Release year",
						last: true,
						columnClasses: "text-right",
					},
				});
			});

			test("should order columns by their order in configuration", () => {
				const data = [sampleRow];
				const columns = { release_year: { label: "Release year" }, title: { label: "Title" } };
				const wrapper = mount({ data, columns });
				const vm = wrapper.vm;

				expect(vm.columnDefinitions).toEqual({
					release_year: {
						...baseColumnDefinition,
						label: "Release year",
						first: true,
					},
					title: {
						...baseColumnDefinition,
						label: "Title",
						last: true,
					},
				});
			});

			test("should remove columns without configuration", () => {
				const data = [sampleRow];
				const columns = { title: { label: "Title" }, release_year: { label: "Release year" } };
				const wrapper = mount({ data, columns });
				const vm = wrapper.vm;

				expect(vm.columnDefinitions).toEqual({
					title: {
						...baseColumnDefinition,
						first: true,
						label: "Title",
					},
					release_year: {
						...baseColumnDefinition,
						label: "Release year",
						last: true,
					},
				});
			});

			test("should remove columns that are explicity marked as hidden", () => {
				const data = [sampleRow];
				const columns = { title: { label: "Title" }, release_year: { hidden: true } };
				const wrapper = mount({ data, columns });
				const vm = wrapper.vm;

				expect(vm.columnDefinitions).toEqual({
					title: {
						...baseColumnDefinition,
						label: "Title",
						first: true,
						last: true,
					},
				});
			});

			test("should respect stored column visibility", () => {
				localStorage.getItem.mockReturnValue(JSON.stringify({ title: false }));

				const columns = { title: { label: "Title" }, release_year: { label: "Release year" } };
				const wrapper = mount({ columns, name: "sample-table" });
				const vm = wrapper.vm;

				expect(vm.columnDefinitions).toEqual({
					title: {
						...baseColumnDefinition,
						label: "Title",
						first: true,
						visible: false,
					},
					release_year: {
						...baseColumnDefinition,
						label: "Release year",
						last: true,
					},
				});

				localStorage.getItem.mockReturnValue(null);
			});
		});

		describe("visibleColumnDefinitions", () => {
			test("should only include visible columns", () => {
				const columns = {
					id: { title: "ID" },
					title: { label: "Title" },
					release_year: { label: "Release year" },
				};

				const wrapper = mount({ columns });
				const vm = wrapper.vm;

				vm.columnVisibility = { title: false };

				expect(Object.keys(vm.columnDefinitions).length).toBe(3);
				expect(Object.keys(vm.visibleColumnDefinitions).length).toBe(2);
			});
		});

		describe("internalData", () => {
			test("should handle there being no data present", () => {
				const wrapper = mount({ data: [] });
				const vm = wrapper.vm;

				expect(vm.internalData).toEqual([]);
			});

			describe("should remove any non-empty objects from the data", () => {
				test.for([
					["boolean (true)", true],
					["boolean (false)", false],
					["number (positive)", 1],
					["number (negative)", -1],
					["number (NaN)", NaN],
					["string (non-empty)", "string"],
					["string (empty)", ""],
					["array (non-empty)", [1, 2, 3]],
					["array (empty)", []],
					["object (empty)", {}],
					["null", null],
					["undefined", undefined],
				])("%s", ([, row]) => {
					const wrapper = mount({ data: [sampleRow, row] });
					const vm = wrapper.vm;

					expect(vm.internalData).toEqual([
						{
							configuration: {
								id: expect.any(String),
							},
							content: standardisedRow,
							raw: sampleRow,
						},
					]);
				});
			});
		});

		describe("haveData", () => {
			test("should detect when no data is present", () => {
				const wrapper = mount({ data: [] });
				const vm = wrapper.vm;

				expect(vm.haveData).toBe(false);
			});

			test("should detect when data is present", () => {
				const wrapper = mount({ data: [sampleRow] });
				const vm = wrapper.vm;

				expect(vm.haveData).toBe(true);
			});
		});

		describe("filteredRows", () => {
			test("should contain all rows by default", () => {
				const secondRow = { id: "234", title: "Big Hero 6", release_year: "2014" };
				const wrapper = mount({ data: [sampleRow, secondRow] });
				const vm = wrapper.vm;

				expect(vm.filteredRows).toHaveLength(2);
				expectToHaveRowWith(vm, "title", "Toy Story");
			});

			test("should display a row matching the current search term, case insensitively", () => {
				const secondRow = { id: "234", title: "Big Hero 6", release_year: "2014" };
				const columns = { title: {}, release_year: {} };
				const wrapper = mount({ data: [sampleRow, secondRow], columns });
				const vm = wrapper.vm;

				vm.searchQuery = "big hero";

				expect(vm.filteredRows).toHaveLength(1);
				expectToHaveRowWith(vm, "title", "Big Hero 6");
			});

			test("should contain no rows if a search term does not match", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				vm.searchQuery = "not found";

				expect(vm.filteredRows).toEqual([]);
			});

			test("should only match a phrase against a single cell", () => {
				const columns = { title: {}, release_year: {} };
				const wrapper = mount({ columns });
				const vm = wrapper.vm;

				vm.searchQuery = "story 1995";

				expect(vm.filteredRows).toEqual([]);

				vm.searchQuery = "story1995";

				expect(vm.filteredRows).toEqual([]);

				vm.searchQuery = "story";

				expect(vm.filteredRows).toHaveLength(1);

				vm.searchQuery = "1995";

				expect(vm.filteredRows).toHaveLength(1);
			});

			test("should skip a column if that column is marked as not searchable", () => {
				const wrapper = mount({ columns: { title: { searchable: false } } });
				const vm = wrapper.vm;

				vm.searchQuery = "Toy Story";

				expect(vm.filteredRows).toEqual([]);
			});

			test("should defer to a column searchableContentCallback if defined", () => {
				const searchableContentCallback = (columnKey) => {
					if (columnKey === "title") {
						return "abcdef";
					}
				};

				const wrapper = mount({
					columns: { title: { searchableContentCallback }, release_year: {} },
				});

				const vm = wrapper.vm;

				vm.searchQuery = "abcdef";

				expect(vm.filteredRows).toHaveLength(1);

				vm.searchQuery = "1995";

				expect(vm.filteredRows).toHaveLength(1);

				vm.searchQuery = "Toy Story";

				expect(vm.filteredRows).toEqual([]);
			});
		});

		describe("sortedRows", () => {
			test("should sort rows by their content", () => {
				const wrapper = mount({
					data: [sampleRow, { id: "234", title: "Big Hero 6", release_year: "2014" }],
					columns: {
						title: { label: "Title" },
					},
				});

				const vm = wrapper.vm;

				vm.sortColumn("title");

				expect(vm.sortedRows[0].content.title.content).toBe("Big Hero 6");
				expect(vm.sortedRows[1].content.title.content).toBe("Toy Story");

				vm.sortColumn("title");

				expect(vm.sortedRows[0].content.title.content).toBe("Toy Story");
				expect(vm.sortedRows[1].content.title.content).toBe("Big Hero 6");
			});
		});

		describe("paginatedRows", () => {
			test("should display a single page of items when more than a single page are available", async () => {
				const data = Array.from({ length: 15 }, (_, i) => ({
					id: i + 1,
					title: `Title ${i + 1}`,
					release_year: 1990 + i,
				}));

				const wrapper = mount({ data });
				const vm = wrapper.vm;

				expect(vm.paginatedRows.length).toBe(10);
				expect(vm.paginatedRows[0].raw).toEqual(expect.objectContaining({ id: 1 }));
			});

			test("should display all items when fewer than a single page are available", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				expect(vm.paginatedRows.length).toBe(1);
			});

			test("should show all rows if pagination is not enabled", () => {
				const data = Array.from({ length: 15 }, (_, i) => ({
					id: i + 1,
					title: `Title ${i + 1}`,
					release_year: 1990 + i,
				}));

				const wrapper = mount({ data, enablePagination: false });
				const vm = wrapper.vm;

				expect(vm.paginatedRows.length).toBe(15);
			});

			test("should re-calculate if sortedColumn is changed", async () => {
				const data = Array.from({ length: 15 }, (_, i) => ({
					id: i + 1,
					title: `Title ${i + 1}`,
					release_year: 2000 - i,
				}));

				const wrapper = mount({ data });
				const vm = wrapper.vm;

				vm.sortedColumn = "title";

				await nextTick();

				expect(vm.paginatedRows[0].raw).toEqual(expect.objectContaining({ id: 1 }));

				vm.sortedColumn = "release_year";

				await nextTick();

				expect(vm.paginatedRows[0].raw).toEqual(expect.objectContaining({ id: 15 }));
			});

			test("should re-calculate if sortDirection is changed", async () => {
				const data = Array.from({ length: 15 }, (_, i) => ({
					id: i + 1,
					title: `Title ${i + 1}`,
					release_year: 2000 - i,
				}));

				const wrapper = mount({ data });
				const vm = wrapper.vm;

				vm.sortedColumn = "title";

				await nextTick();

				expect(vm.paginatedRows[0].raw).toEqual(expect.objectContaining({ id: 1 }));

				vm.sortedColumn = "release_year";

				await nextTick();

				expect(vm.paginatedRows[0].raw).toEqual(expect.objectContaining({ id: 15 }));
			});

			test("should re-calculate if currentPage is changed", async () => {
				const data = Array.from({ length: 15 }, (_, i) => ({
					id: i + 1,
					title: `Title ${i + 1}`,
					release_year: 2000 - i,
				}));

				const wrapper = mount({ data });
				const vm = wrapper.vm;

				vm.currentPage = 2;

				await nextTick();

				expect(vm.paginatedRows.length).toBe(5);
				expect(vm.paginatedRows[0].raw).toEqual(expect.objectContaining({ id: 11 }));
			});
		});

		describe("haveDataToDisplay", () => {
			test("should return false if no data is provided", () => {
				const wrapper = mount({ data: [] });
				const vm = wrapper.vm;

				expect(vm.haveDataToDisplay).toBe(false);
			});

			test("should return true if no search term is present", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				expect(vm.haveDataToDisplay).toBe(true);
			});

			test("should return true if a search produces a result", () => {
				const wrapper = mount({ columns: { title: {} } });
				const vm = wrapper.vm;

				vm.searchQuery = "toy";

				expect(vm.haveDataToDisplay).toBe(true);
			});

			test("should be false if a search produces no results", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				vm.searchQuery = "not found";

				expect(vm.haveDataToDisplay).toBe(false);
			});
		});

		describe("selectedRows", () => {
			test("should update `selectAllRows` if all rows are selected", async () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				vm.selectedRowIds = vm.internalData.map((row) => row.configuration.id);

				await nextTick();

				expect(vm.selectAllRows).toBe(true);
			});

			test("should update `selectAllRows` if a single row is deselected", async () => {
				const wrapper = mount({ data: [sampleRow, sampleRow] });
				const vm = wrapper.vm;

				vm.selectedRowIds = vm.internalData.map((row) => row.configuration.id);

				await nextTick();

				expect(vm.selectAllRows).toBe(true);

				vm.selectedRowIds = [vm.internalData[0].configuration.id];

				await nextTick();

				expect(vm.selectAllRows).toBe(false);
			});
		});
	});

	describe("Methods", () => {
		describe("getRowId", () => {
			test("should retrieve a row ID from configuration", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				const row = { configuration: { id: "abcde" } };

				expect(vm.getRowId(row)).toBe("abcde");
			});

			test("should handle a malformed row", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				const row = { content: {} };

				expect(vm.getRowId(row)).toBe(null);
			});
		});

		describe("getRowContent", () => {
			test("should return the content of a row", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				const row = vm.internalData[0];
				const content = vm.getRowContent(row, "title");

				expect(content).toEqual("Toy Story");
			});

			describe("should ignore invalid cell content", () => {
				test.for([
					["boolean (true)", true],
					["boolean (false)", false],
					["number (NaN)", NaN],
					["string (empty)", ""],
					["object (non-empty)", { property: "value" }],
					["object (empty)", {}],
					["array (non-empty)", [1, 2, 3]],
					["array (empty)", []],
					["null", null],
					["undefined", undefined],
				])("%s", ([, input]) => {
					const wrapper = mount({ data: [{ id: input }] });
					const vm = wrapper.vm;

					const row = vm.internalData[0];
					const content = vm.getRowContent(row, "id");

					expect(content).toEqual("");
				});
			});
		});

		describe("getRawRow", () => {
			test("should retrieve the original raw row data", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				const row = vm.internalData[0];

				expect(vm.getRawRow(row)).toEqual(sampleRow);
			});
		});

		describe("setSearchQuery", () => {
			test("should update the current search query", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				vm.setSearchQuery("Moana");

				expect(vm.searchQuery).toBe("Moana");
			});

			describe("should not update the search query if an invalid input is provided", () => {
				test.for([
					["boolean (true)", true],
					["boolean (false)", false],
					["number (positive)", 1],
					["number (negative)", -1],
					["number (NaN)", NaN],
					["string (empty)", ""],
					["array (empty)", []],
					["object (non-empty)", { property: "value" }],
					["object (empty)", {}],
					["null", null],
					["undefined", undefined],
				])("%s", ([, input]) => {
					const wrapper = mount();
					const vm = wrapper.vm;

					vm.setSearchQuery(input);

					expect(vm.searchQuery).toBe("");
				});
			});
		});

		describe("getSortInstruction", () => {
			test("prompts to sort an unsorted column", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				expect(vm.getSortInstruction("title")).toBe("(sortable — activate to sort ascending)");
			});

			test("describes the ascending state and offers descending", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				vm.sortedColumn = "title";
				vm.sortDirection = "ascending";

				expect(vm.getSortInstruction("title")).toBe(
					"(sorted ascending — activate to sort descending)",
				);
			});

			test("describes the descending state and offers ascending", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				vm.sortedColumn = "title";
				vm.sortDirection = "descending";

				expect(vm.getSortInstruction("title")).toBe(
					"(sorted descending — activate to sort ascending)",
				);
			});
		});
	});
});

/**
 * Ensure that the given instance has a row containing the specified key and
 * value.
 */
function expectToHaveRowWith(vm, key, value) {
	const row = vm.internalData.find((row) => get(row, `content.${key}.content`) === value);

	return expect(row).toBeDefined();
}
