import DataTable from "./data-table.vue";
import DataTableFooter from "./fragments/data-table-footer/data-table-footer.vue";
import DataTableStatus from "./fragments/data-table-status/data-table-status.vue";
import DataTableToolbar from "./fragments/data-table-toolbar/data-table-toolbar.vue";
import { createDeepMount, createMount } from "@lewishowles/testing/vue";
import { afterEach, describe, expect, test, vi } from "vite-plus/test";
import { getPathValue } from "@lewishowles/helpers/object";
import { defineComponent, h, nextTick, ref } from "vue";

const sampleRow = { id: "123", title: "Toy Story", release_year: "1995" };
const defaultProps = { data: [sampleRow] };
const mount = createMount(DataTable, { props: defaultProps });
const deepMount = createDeepMount(DataTable, { props: defaultProps });

describe("data-table", () => {
	afterEach(() => {
		vi.restoreAllMocks();
	});

	// A mock "standardised" row as generated by the data-table internals for
	// testing.
	const standardisedRow = {
		id: {
			configuration: {
				searchable: "123",
				sortable: "123",
			},
			content: "123",
		},
		title: {
			configuration: {
				searchable: "toy story",
				sortable: "toy story",
			},
			content: "Toy Story",
		},
		release_year: {
			configuration: {
				searchable: "1995",
				sortable: "1995",
			},
			content: "1995",
		},
	};

	// A standard column definition for testing.
	const baseColumnDefinition = {
		first: false,
		last: false,
		sortable: true,
		tabularNums: false,
		visible: true,
	};

	describe("Initialisation", () => {
		test("should exist as a Vue component", () => {
			const wrapper = mount();

			expect(wrapper.vm).toBeTypeOf("object");
		});

		test("defaults the narrow layout to cards", () => {
			const wrapper = mount();

			expect(wrapper.props("narrowLayout")).toBe("cards");
		});
	});

	describe("Render", () => {
		test.each(["client", "server"])(
			"Keeps toolbar controls when %s data becomes empty",
			async (mode) => {
				// Start with rows to verify that filtering preserves the existing controls.
				const wrapper = deepMount({
					props: {
						mode,
						totalRows: 1,
						name: `empty-results-${mode}`,
						columns: { title: { label: "Title" }, release_year: { label: "Release year" } },
						loading: false,
						error: null,
					},
					slots: {
						"post-search": '<button type="button">Filter rows</button>',
						"pre-configuration": '<button type="button">Export rows</button>',
					},
				});

				// The toolbar must stay mounted as results disappear and return.
				const toolbar = wrapper.get('[data-test="data-table-toolbar"]').element;

				await wrapper.setProps({ data: [], totalRows: 0 });

				expect(wrapper.get('[data-test="data-table-toolbar"]').element).toBe(toolbar);
				expect(wrapper.find('[data-test="data-table-search-input"]').exists()).toBe(true);
				expect(wrapper.get('[data-test="data-table-toolbar"]').text()).toContain("Filter rows");
				expect(wrapper.get('[data-test="data-table-toolbar"]').text()).toContain("Export rows");
				expect(wrapper.find('[data-test="data-table-display-options"]').exists()).toBe(true);

				expect(
					wrapper
						.findAll('[data-test="data-table-columns-checkbox"]')
						.map((checkbox) => checkbox.text()),
				).toEqual(["Title", "Release year"]);

				expect(
					wrapper.findAll('[data-test="data-table-columns"] input[type="checkbox"]'),
				).toHaveLength(2);

				expect(wrapper.get('[data-test="data-table-no-data"]').text()).toContain(
					"No data to display.",
				);

				expect(wrapper.find('[data-test="data-table-table"]').exists()).toBe(false);

				await wrapper.setProps({ data: [sampleRow], totalRows: 1 });

				expect(wrapper.get('[data-test="data-table-toolbar"]').element).toBe(toolbar);
				expect(wrapper.find('[data-test="data-table-no-data"]').exists()).toBe(false);
				expect(wrapper.find('[data-test="data-table-table"]').exists()).toBe(true);
			},
		);

		test("Shows a custom empty message and hides the toolbar when it has nothing to show", () => {
			// Empty tables retain the same toolbar visibility condition as populated tables.
			const wrapper = deepMount({
				props: { data: [], enableSearch: false },
				slots: { "no-data-message": "No matching records." },
			});

			expect(wrapper.find('[data-test="data-table-toolbar"]').exists()).toBe(false);

			expect(wrapper.get('[data-test="data-table-no-data"]').text()).toContain(
				"No matching records.",
			);
		});

		test("hides the toolbar when search, configuration, and toolbar slots are absent", () => {
			const wrapper = deepMount({ enableSearch: false });

			expect(wrapper.find('[data-test="data-table-toolbar"]').exists()).toBe(false);
		});

		test("forwards column content and heading slots to the table", () => {
			const wrapper = deepMount({
				props: { columns: { title: { label: "Title" } }, enableSearch: false },
				slots: {
					title: ({ cell }) => `Film: ${cell}`,
					title_heading: ({ label }) => `Film ${label}`,
				},
			});

			expect(wrapper.get('[data-test="data-table-heading"]').text()).toContain("Film Title");
			expect(wrapper.get('[data-test="data-table-field-value"]').text()).toBe("Film: Toy Story");
		});

		test("hides the configured actions column and sort buttons", () => {
			const wrapper = deepMount({
				props: {
					columns: { title: { label: "Title" }, actions: { hidden: true } },
					enableSearch: false,
					enableSort: false,
				},
				slots: { actions: ({ row }) => row.id },
			});

			expect(wrapper.findAll('[data-test="data-table-heading"]')).toHaveLength(1);
			expect(wrapper.findAll('[data-test="data-table-cell"]')).toHaveLength(1);
			expect(wrapper.find('[data-test="data-table-sort"]').exists()).toBe(false);
		});

		test("keeps an initial sort on the second column without updating server state", () => {
			const wrapper = deepMount({
				props: {
					columns: { title: { label: "Title" }, release_year: { label: "Release year" } },
					enableSearch: false,
					error: null,
					loading: false,
					mode: "server",
					state: { sort: { column: "release_year", direction: "descending" } },
					totalRows: 1,
				},
			});

			const select = wrapper.get('[data-test="data-table-card-sort-column"] select');

			expect(select.element.value).toBe("release_year");
			expect(wrapper.emitted("update:state")).toBeUndefined();
		});

		test("forwards a caption slot added after mount and removes it again", async () => {
			const host = defineComponent({
				setup() {
					const showCaption = ref(false);

					return { showCaption };
				},
				render() {
					return h(
						DataTable,
						{ data: [sampleRow], columns: { title: { label: "Title" } }, enableSearch: false },
						this.showCaption ? { caption: () => "Films" } : {},
					);
				},
			});

			const wrapper = createDeepMount(host)();

			expect(wrapper.find("caption").exists()).toBe(false);

			wrapper.vm.showCaption = true;

			await nextTick();

			expect(wrapper.get("caption").text()).toBe("Films");

			wrapper.vm.showCaption = false;

			await nextTick();

			expect(wrapper.find("caption").exists()).toBe(false);
		});

		test.each([
			["caption", {}],
			["sorted-hint", { state: { sort: { column: "title", direction: "ascending" } } }],
			["sort-instruction", {}],
			["sort-by-label", {}],
			["sort-ascending-label", { state: { sort: { column: "title", direction: "ascending" } } }],
			["sort-descending-label", { state: { sort: { column: "title", direction: "descending" } } }],
			["sort-direction-label", { state: { sort: { column: "title", direction: "ascending" } } }],
			["loading-label", { mode: "server", loading: true, error: null, totalRows: 1 }],
			["error", { mode: "server", loading: false, error: "Unavailable", totalRows: 1 }],
			["select-all-rows-label", { enableSelection: true }],
			["select-row-label", { enableSelection: true }],
		])("forwards the %s slot to the table", (slotName, props) => {
			const wrapper = deepMount({
				props: { columns: { title: { label: "Title" } }, enableSearch: false, ...props },
				slots: { [slotName]: "Forwarded table copy" },
			});

			expect(wrapper.text()).toContain("Forwarded table copy");
		});

		test("should expose the component styling hook", () => {
			const wrapper = mount();

			expect(wrapper.attributes("data-component")).toBe("data-table");
		});
	});

	describe("Server mode", () => {
		test("Passes a disabled controlled sort to the status fragment", () => {
			const wrapper = deepMount({
				props: {
					columns: { title: { label: "Title" } },
					enableSort: false,
					error: null,
					loading: false,
					mode: "server",
					state: {
						page: 1,
						itemsPerPage: 10,
						sort: { column: "title", direction: "descending" },
						filters: { search: "" },
					},
					totalRows: 1,
				},
			});

			expect(wrapper.findComponent(DataTableStatus).props()).toMatchObject({
				enableSort: false,
				sortColumn: null,
				ascending: true,
			});
		});

		test("warns when required server props are missing", () => {
			const warning = vi.spyOn(console, "warn").mockImplementation(() => {});

			mount({ mode: "server" });

			expect(warning).toHaveBeenCalledWith(
				"[data-table] Server mode requires `totalRows`, `loading`, and `error` props.",
			);
		});

		test("renders the supplied page without applying local search, sort, or pagination", async () => {
			const firstRow = { id: "a", title: "Zulu" };
			const secondRow = { id: "b", title: "Alpha" };

			const wrapper = mount({
				columns: { title: { label: "Title" } },
				data: [firstRow, secondRow],
				error: null,
				loading: false,
				mode: "server",
				state: {
					page: 1,
					itemsPerPage: 10,
					sort: null,
					filters: { search: "" },
				},
				totalRows: 25,
			});

			const vm = wrapper.vm;

			vm.searchQuery = "Alpha";
			vm.sortColumn("title");

			await nextTick();

			expect(vm.filteredRows.map((row) => row.raw)).toEqual([firstRow, secondRow]);
			expect(vm.sortedRows.map((row) => row.raw)).toEqual([firstRow, secondRow]);
			expect(vm.paginatedRows.map((row) => row.raw)).toEqual([firstRow, secondRow]);
			expect(vm.rowCount).toBe(25);

			const stateUpdates = wrapper.emitted("update:state").map(([nextState]) => nextState);

			expect(stateUpdates).toEqual(
				expect.arrayContaining([
					expect.objectContaining({ filters: { search: "Alpha" }, page: 1 }),
					expect.objectContaining({ sort: { column: "title", direction: "ascending" } }),
				]),
			);
		});

		test("keeps search controls available when a server search has no results", () => {
			const wrapper = mount({
				columns: { title: { label: "Title" } },
				data: [],
				error: null,
				loading: false,
				mode: "server",
				state: {
					page: 1,
					itemsPerPage: 10,
					sort: null,
					filters: { search: "Missing" },
				},
				totalRows: 0,
			});

			expect(wrapper.findComponent(DataTableToolbar).exists()).toBe(true);
			expect(wrapper.findComponent(DataTableFooter).props("haveDataToDisplay")).toBe(false);
		});

		test("passes the controlled server page size to the footer", () => {
			const wrapper = mount({
				data: [sampleRow],
				error: null,
				loading: false,
				mode: "server",
				state: {
					page: 1,
					itemsPerPage: 25,
					sort: null,
					filters: {},
				},
				totalRows: 100,
			});

			expect(wrapper.findComponent(DataTableFooter).props("itemsPerPage")).toBe(25);
		});

		test("reports page-scoped selection against the full server total", async () => {
			const wrapper = mount({
				columns: { title: { label: "Title" } },
				data: [
					{ id: "a", title: "Alpha" },
					{ id: "b", title: "Beta" },
				],
				enableSelection: true,
				error: null,
				loading: false,
				mode: "server",
				state: {
					page: 1,
					itemsPerPage: 10,
					sort: null,
					filters: {},
				},
				totalRows: 20,
			});

			wrapper.vm.selectAllRows = true;
			wrapper.vm.toggleAllRows();

			await nextTick();

			expect(wrapper.findComponent(DataTableStatus).props()).toMatchObject({
				allSelected: false,
				enableSelection: true,
				selectedCount: 2,
				totalCount: 20,
			});
		});

		test("warns when selectable server rows do not contain the configured row key", () => {
			const warning = vi.spyOn(console, "warn").mockImplementation(() => {});

			mount({
				columns: { title: { label: "Title" } },
				data: [{ uuid: "a", title: "Alpha" }],
				enableSelection: true,
				error: null,
				loading: false,
				mode: "server",
				state: {
					page: 1,
					itemsPerPage: 10,
					sort: null,
					filters: {},
				},
				totalRows: 1,
			});

			expect(warning).toHaveBeenCalledWith(
				'[data-table] Selectable server rows need a stable value at `rowKey` path "id".',
			);
		});

		test("preserves selected raw rows when the server page changes", async () => {
			const firstRow = { id: "a", title: "Alpha" };
			const secondRow = { id: "b", title: "Beta" };

			const wrapper = mount({
				columns: { title: { label: "Title" } },
				data: [firstRow],
				enableSelection: true,
				error: null,
				loading: false,
				mode: "server",
				state: {
					page: 1,
					itemsPerPage: 10,
					sort: null,
					filters: {},
				},
				totalRows: 20,
			});

			const vm = wrapper.vm;

			vm.selectedRowIds = [vm.internalData[0].configuration.id];

			await nextTick();
			await wrapper.setProps({ data: [secondRow] });
			await nextTick();

			expect(wrapper.emitted("update:modelValue").at(-1)[0]).toEqual([firstRow]);
			expect(vm.selectedRowCount).toBe(1);
		});

		test("reports server pagination changes through state", async () => {
			const wrapper = mount({
				data: [sampleRow],
				error: null,
				loading: false,
				mode: "server",
				state: {
					page: 1,
					itemsPerPage: 10,
					sort: null,
					filters: {},
				},
				totalRows: 25,
			});

			wrapper.vm.currentPage = 2;

			await nextTick();

			expect(wrapper.emitted("update:state").at(-1)[0]).toMatchObject({ page: 2 });
		});
	});

	describe("Computed", () => {
		describe("columnDefinitions", () => {
			test("should handle there being no data present", () => {
				const wrapper = mount({ data: [] });
				const vm = wrapper.vm;

				expect(vm.columnDefinitions).toEqual({});
			});

			test("should determine which column is first, and which is last", () => {
				const columns = {
					id: { label: "ID" },
					title: { label: "Title" },
					release_year: { label: "Release year" },
				};

				const wrapper = mount({ columns });
				const vm = wrapper.vm;

				expect(vm.columnDefinitions).toEqual({
					id: {
						...baseColumnDefinition,
						label: "ID",
						first: true,
					},
					title: {
						...baseColumnDefinition,
						label: "Title",
					},
					release_year: {
						...baseColumnDefinition,
						label: "Release year",
						last: true,
					},
				});
			});

			test("should retrieve column configuration where found", () => {
				const columns = {
					title: { label: "Title" },
					release_year: { label: "Release year", columnClasses: "text-right" },
				};

				const wrapper = mount({ columns });
				const vm = wrapper.vm;

				expect(vm.columnDefinitions).toEqual({
					title: {
						...baseColumnDefinition,
						label: "Title",
						first: true,
					},
					release_year: {
						...baseColumnDefinition,
						label: "Release year",
						last: true,
						columnClasses: "text-right",
					},
				});
			});

			test("should order columns by their order in configuration", () => {
				const data = [sampleRow];
				const columns = { release_year: { label: "Release year" }, title: { label: "Title" } };
				const wrapper = mount({ data, columns });
				const vm = wrapper.vm;

				expect(vm.columnDefinitions).toEqual({
					release_year: {
						...baseColumnDefinition,
						label: "Release year",
						first: true,
					},
					title: {
						...baseColumnDefinition,
						label: "Title",
						last: true,
					},
				});
			});

			test("should remove columns without configuration", () => {
				const data = [sampleRow];
				const columns = { title: { label: "Title" }, release_year: { label: "Release year" } };
				const wrapper = mount({ data, columns });
				const vm = wrapper.vm;

				expect(vm.columnDefinitions).toEqual({
					title: {
						...baseColumnDefinition,
						first: true,
						label: "Title",
					},
					release_year: {
						...baseColumnDefinition,
						label: "Release year",
						last: true,
					},
				});
			});

			test("should remove columns that are explicity marked as hidden", () => {
				const data = [sampleRow];
				const columns = { title: { label: "Title" }, release_year: { hidden: true } };
				const wrapper = mount({ data, columns });
				const vm = wrapper.vm;

				expect(vm.columnDefinitions).toEqual({
					title: {
						...baseColumnDefinition,
						label: "Title",
						first: true,
						last: true,
					},
				});
			});

			test("should respect stored column visibility", () => {
				localStorage.getItem.mockReturnValue(JSON.stringify({ title: false }));

				const columns = { title: { label: "Title" }, release_year: { label: "Release year" } };
				const wrapper = mount({ columns, name: "sample-table" });
				const vm = wrapper.vm;

				expect(vm.columnDefinitions).toEqual({
					title: {
						...baseColumnDefinition,
						label: "Title",
						first: true,
						visible: false,
					},
					release_year: {
						...baseColumnDefinition,
						label: "Release year",
						last: true,
					},
				});

				localStorage.getItem.mockReturnValue(null);
			});
		});

		describe("visibleColumnDefinitions", () => {
			test("should only include visible columns", () => {
				const columns = {
					id: { title: "ID" },
					title: { label: "Title" },
					release_year: { label: "Release year" },
				};

				const wrapper = mount({ columns });
				const vm = wrapper.vm;

				vm.columnVisibility = { title: false };

				expect(Object.keys(vm.columnDefinitions).length).toBe(3);
				expect(Object.keys(vm.visibleColumnDefinitions).length).toBe(2);
			});
		});

		describe("internalData", () => {
			test("should handle there being no data present", () => {
				const wrapper = mount({ data: [] });
				const vm = wrapper.vm;

				expect(vm.internalData).toEqual([]);
			});

			describe("should remove any non-empty objects from the data", () => {
				test.for([
					["boolean (true)", true],
					["boolean (false)", false],
					["number (positive)", 1],
					["number (negative)", -1],
					["number (NaN)", NaN],
					["string (non-empty)", "string"],
					["string (empty)", ""],
					["array (non-empty)", [1, 2, 3]],
					["array (empty)", []],
					["object (empty)", {}],
					["null", null],
					["undefined", undefined],
				])("%s", ([, row]) => {
					const wrapper = mount({ data: [sampleRow, row] });
					const vm = wrapper.vm;

					expect(vm.internalData).toEqual([
						{
							configuration: {
								id: expect.any(String),
							},
							content: standardisedRow,
							raw: sampleRow,
						},
					]);
				});
			});
		});

		describe("haveData", () => {
			test("should detect when no data is present", () => {
				const wrapper = mount({ data: [] });
				const vm = wrapper.vm;

				expect(vm.haveData).toBe(false);
			});

			test("should detect when data is present", () => {
				const wrapper = mount({ data: [sampleRow] });
				const vm = wrapper.vm;

				expect(vm.haveData).toBe(true);
			});
		});

		describe("filteredRows", () => {
			test("should contain all rows by default", () => {
				const secondRow = { id: "234", title: "Big Hero 6", release_year: "2014" };
				const wrapper = mount({ data: [sampleRow, secondRow] });
				const vm = wrapper.vm;

				expect(vm.filteredRows).toHaveLength(2);
				expectToHaveRowWith(vm, "title", "Toy Story");
			});

			test("should display a row matching the current search term, case insensitively", () => {
				const secondRow = { id: "234", title: "Big Hero 6", release_year: "2014" };
				const columns = { title: {}, release_year: {} };
				const wrapper = mount({ data: [sampleRow, secondRow], columns });
				const vm = wrapper.vm;

				vm.searchQuery = "big hero";

				expect(vm.filteredRows).toHaveLength(1);
				expectToHaveRowWith(vm, "title", "Big Hero 6");
			});

			test("should contain no rows if a search term does not match", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				vm.searchQuery = "not found";

				expect(vm.filteredRows).toEqual([]);
			});

			test("should only match a phrase against a single cell", () => {
				const columns = { title: {}, release_year: {} };
				const wrapper = mount({ columns });
				const vm = wrapper.vm;

				vm.searchQuery = "story 1995";

				expect(vm.filteredRows).toEqual([]);

				vm.searchQuery = "story1995";

				expect(vm.filteredRows).toEqual([]);

				vm.searchQuery = "story";

				expect(vm.filteredRows).toHaveLength(1);

				vm.searchQuery = "1995";

				expect(vm.filteredRows).toHaveLength(1);
			});

			test("should skip a column if that column is marked as not searchable", () => {
				const wrapper = mount({ columns: { title: { searchable: false } } });
				const vm = wrapper.vm;

				vm.searchQuery = "Toy Story";

				expect(vm.filteredRows).toEqual([]);
			});

			test("should defer to a column searchableContentCallback if defined", () => {
				const searchableContentCallback = (columnKey) => {
					if (columnKey === "title") {
						return "abcdef";
					}
				};

				const wrapper = mount({
					columns: { title: { searchableContentCallback }, release_year: {} },
				});

				const vm = wrapper.vm;

				vm.searchQuery = "abcdef";

				expect(vm.filteredRows).toHaveLength(1);

				vm.searchQuery = "1995";

				expect(vm.filteredRows).toHaveLength(1);

				vm.searchQuery = "Toy Story";

				expect(vm.filteredRows).toEqual([]);
			});
		});

		describe("sortedRows", () => {
			test("should sort rows by their content", () => {
				const wrapper = mount({
					data: [sampleRow, { id: "234", title: "Big Hero 6", release_year: "2014" }],
					columns: {
						title: { label: "Title" },
					},
				});

				const vm = wrapper.vm;

				vm.sortColumn("title");

				expect(vm.sortedRows[0].content.title.content).toBe("Big Hero 6");
				expect(vm.sortedRows[1].content.title.content).toBe("Toy Story");

				vm.sortColumn("title");

				expect(vm.sortedRows[0].content.title.content).toBe("Toy Story");
				expect(vm.sortedRows[1].content.title.content).toBe("Big Hero 6");
			});
		});

		describe("paginatedRows", () => {
			test("should display a single page of items when more than a single page are available", async () => {
				const data = Array.from({ length: 15 }, (_, i) => ({
					id: i + 1,
					title: `Title ${i + 1}`,
					release_year: 1990 + i,
				}));

				const wrapper = mount({ data });
				const vm = wrapper.vm;

				expect(vm.paginatedRows.length).toBe(10);
				expect(vm.paginatedRows[0].raw).toEqual(expect.objectContaining({ id: 1 }));
			});

			test("should display all items when fewer than a single page are available", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				expect(vm.paginatedRows.length).toBe(1);
			});

			test("should show all rows if pagination is not enabled", () => {
				const data = Array.from({ length: 15 }, (_, i) => ({
					id: i + 1,
					title: `Title ${i + 1}`,
					release_year: 1990 + i,
				}));

				const wrapper = mount({ data, enablePagination: false });
				const vm = wrapper.vm;

				expect(vm.paginatedRows.length).toBe(15);
			});

			test("Recalculates paginated rows when the sorted column changes", async () => {
				const data = Array.from({ length: 15 }, (_, i) => ({
					id: i + 1,
					title: `Title ${i + 1}`,
					release_year: 2000 - i,
				}));

				const wrapper = mount({
					columns: { title: { label: "Title" }, release_year: { label: "Release year" } },
					data,
				});

				const vm = wrapper.vm;

				vm.sortColumn("title");

				await nextTick();

				expect(vm.paginatedRows[0].raw).toEqual(expect.objectContaining({ id: 1 }));

				vm.sortColumn("release_year");

				await nextTick();

				expect(vm.paginatedRows[0].raw).toEqual(expect.objectContaining({ id: 15 }));
			});

			test("Recalculates paginated rows when the sort direction changes", async () => {
				const data = Array.from({ length: 15 }, (_, i) => ({
					id: i + 1,
					title: `Title ${i + 1}`,
					release_year: 2000 - i,
				}));

				const wrapper = mount({
					columns: { release_year: { label: "Release year" } },
					data,
				});

				const vm = wrapper.vm;

				vm.sortColumn("release_year");

				await nextTick();

				expect(vm.paginatedRows[0].raw).toEqual(expect.objectContaining({ id: 15 }));

				vm.sortColumn("release_year");

				await nextTick();

				expect(vm.paginatedRows[0].raw).toEqual(expect.objectContaining({ id: 1 }));
			});

			test("should re-calculate if currentPage is changed", async () => {
				const data = Array.from({ length: 15 }, (_, i) => ({
					id: i + 1,
					title: `Title ${i + 1}`,
					release_year: 2000 - i,
				}));

				const wrapper = mount({ data });
				const vm = wrapper.vm;

				vm.currentPage = 2;

				await nextTick();

				expect(vm.paginatedRows.length).toBe(5);
				expect(vm.paginatedRows[0].raw).toEqual(expect.objectContaining({ id: 11 }));
			});
		});

		describe("haveDataToDisplay", () => {
			test("should return false if no data is provided", () => {
				const wrapper = mount({ data: [] });
				const vm = wrapper.vm;

				expect(vm.haveDataToDisplay).toBe(false);
			});

			test("should return true if no search term is present", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				expect(vm.haveDataToDisplay).toBe(true);
			});

			test("should return true if a search produces a result", () => {
				const wrapper = mount({ columns: { title: {} } });
				const vm = wrapper.vm;

				vm.searchQuery = "toy";

				expect(vm.haveDataToDisplay).toBe(true);
			});

			test("should be false if a search produces no results", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				vm.searchQuery = "not found";

				expect(vm.haveDataToDisplay).toBe(false);
			});
		});

		describe("selectedRows", () => {
			test("should update `selectAllRows` if all rows are selected", async () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				vm.selectedRowIds = vm.internalData.map((row) => row.configuration.id);

				await nextTick();

				expect(vm.selectAllRows).toBe(true);
			});

			test("should update `selectAllRows` if a single row is deselected", async () => {
				const wrapper = mount({ data: [sampleRow, sampleRow] });
				const vm = wrapper.vm;

				vm.selectedRowIds = vm.internalData.map((row) => row.configuration.id);

				await nextTick();

				expect(vm.selectAllRows).toBe(true);

				vm.selectedRowIds = [vm.internalData[0].configuration.id];

				await nextTick();

				expect(vm.selectAllRows).toBe(false);
			});
		});
	});

	describe("Methods", () => {
		describe("setSearchQuery", () => {
			test("should update the current search query", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				vm.setSearchQuery("Moana");

				expect(vm.searchQuery).toBe("Moana");
			});

			test("should clear the current search query when an empty string is provided", () => {
				const wrapper = mount();
				const vm = wrapper.vm;

				vm.setSearchQuery("Moana");
				vm.setSearchQuery("");

				expect(vm.searchQuery).toBe("");
			});

			describe("should not update the search query if an invalid input is provided", () => {
				test.for([
					["boolean (true)", true],
					["boolean (false)", false],
					["number (positive)", 1],
					["number (negative)", -1],
					["number (NaN)", NaN],
					["array (empty)", []],
					["object (non-empty)", { property: "value" }],
					["object (empty)", {}],
					["null", null],
					["undefined", undefined],
				])("%s", ([, input]) => {
					const wrapper = mount();
					const vm = wrapper.vm;

					vm.setSearchQuery(input);

					expect(vm.searchQuery).toBe("");
				});
			});
		});
	});
});

/**
 * Ensure that the given instance has a row containing the specified key and
 * value.
 */
function expectToHaveRowWith(vm, key, value) {
	const row = vm.internalData.find((row) => getPathValue(row, `content.${key}.content`) === value);

	return expect(row).toBeDefined();
}
